### PR TITLE
PR  #1 completed successfully.

### PR DESCRIPTION
**Pull request by Shubbu-07**
I've added all the information that ReadMe.md file should contain it. Please check it out.

### CODE REVIEW

**Comment by itsankitbhusal** [comment]
Can you, adjust the navbar height, seems really big navbar.
image

----
After updating updated file push the changes and make sure to take a screenshot and leave it in the chat

**Comment by Shubbu-07** [comment]
By mistake I've pushed the commit of #2 in same PR. I want to create separate PR for both can help me out?

**Comment by itsankitbhusal** [comment]
this is good for now, you only need to fix the navbar height for now

**Comment by Shubbu-07** [comment]
Screenshot 2023-10-16 193654

I've changed the logo & added the better one. Navbar height is also fixed. Will it be good?

**Review by itsankitbhusal — APPROVED** [review]
Looks good to me

**Pull request merged**
